name: template

on:
  push:
    branches: [ template ]

jobs:
  template-tgt:
    name: Template Action
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          ls
